name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhiredis-dev build-essential cmake

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install hiredis

      - name: Install system dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install hiredis:x64-windows
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
          choco install cmake -y

      - name: Install dependencies
        run: npm ci

      - name: Build native module (Unix)
        if: matrix.os != 'windows-latest'
        run: npm run build
        env:
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}

      - name: Build native module (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          node-gyp rebuild
          mkdir -p prebuilds\win32-x64
          copy build\Release\hyperlimit.node prebuilds\win32-x64\node.napi.node
          copy %VCPKG_ROOT%\installed\x64-windows\bin\*.dll build\Release\
          copy %VCPKG_ROOT%\installed\x64-windows\bin\*.dll prebuilds\win32-x64\
        env:
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}

      - name: Upload prebuilt binaries
        uses: actions/upload-artifact@v3
        with:
          name: prebuilds-${{ matrix.os }}-${{ matrix.node-version }}
          path: prebuilds/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@hyperlimit'
          always-auth: true

      - name: Update version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          npm version ${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Download all prebuilds
        uses: actions/download-artifact@v3
        with:
          path: prebuilds-all

      - name: Merge prebuilds
        run: |
          mkdir -p prebuilds
          cp -r prebuilds-all/*/* prebuilds/

      - name: Create packages
        run: |
          # Create core package
          mkdir -p dist/hyperlimit
          cp -r prebuilds package.json README.md LICENSE dist/hyperlimit/
          cd dist/hyperlimit
          # Update package.json for core package
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@hyperlimit/core';
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          npm pack
          cd ../..

          # Create Express middleware package
          mkdir -p dist/hyperlimit-express
          cp -r src/middleware-express.js package.json README.md LICENSE dist/hyperlimit-express/
          cd dist/hyperlimit-express
          # Update package.json for Express middleware
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@hyperlimit/express';
            pkg.description = 'Express middleware for HyperLimit rate limiter';
            pkg.main = 'middleware-express.js';
            pkg.dependencies = {
              '@hyperlimit/core': pkg.version,
              'express': '^4.17.1'
            };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          npm pack
          cd ../..

          # Create Fastify middleware package
          mkdir -p dist/hyperlimit-fastify
          cp -r src/middleware-fastify.js package.json README.md LICENSE dist/hyperlimit-fastify/
          cd dist/hyperlimit-fastify
          # Update package.json for Fastify middleware
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@hyperlimit/fastify';
            pkg.description = 'Fastify middleware for HyperLimit rate limiter';
            pkg.main = 'middleware-fastify.js';
            pkg.dependencies = {
              '@hyperlimit/core': pkg.version,
              'fastify': '^4.0.0'
            };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          npm pack
          cd ../..

          # Create HyperExpress middleware package
          mkdir -p dist/hyperlimit-hyperexpress
          cp -r src/middleware-hyperexpress.js package.json README.md LICENSE dist/hyperlimit-hyperexpress/
          cd dist/hyperlimit-hyperexpress
          # Update package.json for HyperExpress middleware
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@hyperlimit/hyperexpress';
            pkg.description = 'HyperExpress middleware for HyperLimit rate limiter';
            pkg.main = 'middleware-hyperexpress.js';
            pkg.dependencies = {
              '@hyperlimit/core': pkg.version,
              'hyper-express': '^6.0.0'
            };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          npm pack
          cd ../..

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          # Create local .npmrc file
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          
          # Publish packages
          cd dist/hyperlimit && npm publish --access public
          cd ../hyperlimit-express && npm publish --access public
          cd ../hyperlimit-fastify && npm publish --access public
          cd ../hyperlimit-hyperexpress && npm publish --access public 