name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests
      run: |
        # Run core tests
        npm run test:core

        # Run middleware tests
        npm run test:middleware

        # Run integration tests
        npm run test:integration

    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.os }}-node-${{ matrix.node-version }}
        path: coverage/ 